app/BotGard/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from config_tables.admin import ConfigurableTable
from botman.views import index_page

urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),

    url(r'^individual/',    include('individuals.urls')),
    url(r'^botman/',        include('botman.urls')),
    url(r'^$',              index_page, name="index"),
    url(r'^species/',       include('species.urls')),
    url(r'^seedcatalog/',   include('seedcatalog.urls')),
    url(r'^tickets/',       include('tickets.urls')),
    url(r'^labels/',        include('labels.urls')),
    url(r'^sidebar/',       include('sidebar.urls')),
    url(r'^ajax/',          include('ajax.urls')),
)

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/ajax/urls.py
from django.conf.urls import url

from . import views

app_name = "ajax"
urlpatterns = [
    url(r'^model/model.json/?$',            views.model_fieldvalues_json, name='model_json'),
    url(r'^model/choices.json/?$',          views.choice_fieldvalues_json, name='choices_json'),
]

app/seedcatalog/urls.py
from django.conf.urls import url

from . import views

app_name = "seedcatalog"
urlpatterns = [
    url(r'^edit/(?P<forId>\d+)$',                               views.edit_seeds, name='edit_seeds'),
    url(r'^add/(?P<seedId>\d+)/to/(?P<catalogId>\d+)/$',        views.add_seed_to_catalog, name='add_seed'),
    url(r'^add/(?P<seedId>\d+)/toCurrent/$',                    views.add_seed_to_current_catalog, name='add_seed_to_current'),
    url(r'^remove/(?P<seedId>\d+)/from/(?P<catalogId>\d+)/$',   views.remove_seed_from_catalog, name='remove_seed'),
    url(r'^generate/(?P<catalogId>\d+)/$',                      views.generate_request, name='generate'),
    url(r'^debug/(?P<catalogId>\d+)/$',                         views.debug_view, name='debug'),
    url(r'^duplicate/(?P<catalogId>\d+)/$',                     views.duplicate_catalog_request, name="duplicate_catalog"),
    url(r'^finalize/(?P<catalogId>\d+)/$',                      views.finalize_catalog_request, name="finalize_catalog"),
]

app/seedcatalog/models.py
import os
import datetime
import time

from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.html import escape
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe


class SeedCatalog(models.Model):
    class Meta:
        verbose_name = _('seed catalog')
        verbose_name_plural = _('seed catalogs')
        permissions = (("can_finalize_catalog", _("can finalize a seed catalog")),)

    _id_field = "release_date"

    # validity and creation dates
    release_date = models.DateField(verbose_name=_('release date'), blank=False, null=False)
    valid_until_date = models.DateField(verbose_name=_('valid until'), blank=True, null=True)
    is_finalized = models.BooleanField(verbose_name=_("finalized"), default=False, editable=False)

    # text parts
    title = models.TextField(verbose_name=_('Title of catalog'))
    title_sub = models.TextField(verbose_name=_('Sub-title of catalog'), null=True, blank=True)

    copyright_note = models.TextField(verbose_name=_('copyright note'), max_length=10000,
                                      blank=True, help_text=_('LaTeX syntax allowed'))
    preface = models.TextField(verbose_name=_('preface'), max_length=10000, blank=True,
                               help_text=_('LaTeX syntax allowed'))
    notes = models.TextField(verbose_name=_('notes'), max_length=10000, blank=True,
                             help_text=_('LaTeX syntax allowed'))

    # connections to seeds/individuals
    seed = models.ManyToManyField('individuals.Individual', verbose_name=_('seed'), blank=True)

    debug_output = models.TextField(verbose_name=_("debug output"), editable=False, blank=True, default="")

    def __str__(self):
        return '%s %d %s' % (_('seed catalog'), self.pk, self.release_date)
    __str__.admin_order_field = 'release_date'

    def manage_seed_decorator(self):
        if self.is_finalized:
            return _("finalized")
        url = reverse("seedcatalog:edit_seeds", args=(self.pk,))
        return mark_safe('<a href="%s">%s</a>' % (url, _('Edit %d seeds in catalog') % self.seed.count()))
    manage_seed_decorator.short_description = _('Edit seeds in catalog')
    manage_seed_decorator.exclude_csv = True

    def pdf_file_decorator(self):
        fileTarget = '%s/pdf/catalog/catalog-%d.pdf' % (settings.MEDIA_ROOT, self.pk)
        urlTarget = '%s/pdf/catalog/catalog-%d.pdf' % (settings.MEDIA_URL, self.pk)
        if os.path.isfile(fileTarget):
            html = '<a href="%s?%s">PDF (%s)</a>' % (
                urlTarget,
                escape(datetime.datetime.now().isoformat()),
                "%s" % time.ctime(os.path.getctime(fileTarget)),
            )
        else:
            html = _("not yet created")
        if self.debug_output:
            url = reverse("seedcatalog:debug", args=(self.pk,))
            # Translators: show seed catalog debug output link hover text
            html += ' (<a href="%s" title="%s">***</a>)' % (url, _("show debug output"))
        return mark_safe(html)
    pdf_file_decorator.short_description = 'PDF'
    pdf_file_decorator.exclude_csv = True

    def generate_catalog_decorator(self):
        url = reverse("seedcatalog:generate", args=(self.pk, ))
        return mark_safe('<a href="%s">%s</a>' % (url, _("generate catalog")))
    generate_catalog_decorator.short_description = _('create')
    generate_catalog_decorator.exclude_csv = True

    def create_duplicate(self):
        """Create a clone of the current catalog
        Returns the new instance"""
        today = datetime.date.today()
        cat = SeedCatalog.objects.create(
            release_date=today,
            valid_until_date=today,
            is_finalized=False,
            title=self.title,
            title_sub=self.title_sub,
            copyright_note=self.copyright_note,
            preface=self.preface,
            notes=self.notes,
        )
        for seed in self.seed.all():
            cat.seed.add(seed)
        cat.save()
        return cat

app/seedcatalog/views.py
from django.template import Context, loader
from django.http import HttpResponse, HttpResponseRedirect
from django.utils.translation import gettext_lazy as _
from django.shortcuts import render

from seedcatalog.models import *
from individuals.models import *
from tools.permissions import *
from tools.admin_extensions import minimal_admin_context
from config_app import register_key


def render_catalog_edit(request, catalog: SeedCatalog, inline: bool = False, message: str = None):
    seeds = catalog.seed.all()

    allseeds = Individual.objects.filter(seed_available=True)

    ctx = minimal_admin_context(
        request, SeedCatalog,
        title=_("Samen im Katalog bearbeiten"),
        extra={
            'seeds': seeds,
            'allseeds': allseeds,
            'catalog': catalog,
            'catalog_message': message,
        }
    )

    template = 'seedcatalog/edit_inline.html' if inline else 'seedcatalog/edit_page.html'
    return render(request, template, ctx)


@write_permission_required
def edit_seeds(request, forId):
    try:
        catalog = SeedCatalog.objects.get(id=forId)
    except SeedCatalog.DoesNotExist:
        return HttpResponse(_('Catalog not found.'), status=404)

    return render_catalog_edit(request, catalog)


@write_permission_required
def remove_seed_from_catalog(request, seedId, catalogId):
    try:
        seed = Individual.objects.get(id=seedId)
    except Individual.DoesNotExist:
        return HttpResponse(_('Individual/Seed not found'), status=404)

    try:
        catalog = SeedCatalog.objects.get(id=catalogId)
    except SeedCatalog.DoesNotExist:
        return HttpResponse(_('Seed catalog not found'), status=404)

    catalog.seed.remove(seed)
    catalog.save()

    if "_redirect" in request.GET:
        return HttpResponseRedirect(request.GET["_redirect"])

    message = _('%(seed)s removed from %(catalog)s') % {'seed': seed, 'catalog': catalog}

    return render_catalog_edit(
        request=request, catalog=catalog,
        inline="inline" in request.GET,
        message=message,
    )


@write_permission_required
def add_seed_to_current_catalog(request, seedId):
    try:
        seed = Individual.objects.get(id=seedId)
    except:
        return HttpResponse(_('Individual/seed not found.'))

    try:
        catalog = SeedCatalog.objects.latest('pk')
    except:
        return HttpResponse(_('Seed catalog not found'))

    catalog.seed.add(seed)
    catalog.save()

    seed.seed_available = True
    seed.save()

    if "_redirect" in request.GET:
        return HttpResponseRedirect(request.GET["_redirect"])

    return HttpResponse(
        _('added %(seed)s to %(catalog)s (seeds are automatically marked as present)')
            % { 'seed':str(seed), 'catalog':str(catalog) })


@write_permission_required
def add_seed_to_catalog(request, seedId, catalogId):
    try:
        seed = Individual.objects.get(id=seedId)
    except:
        return HttpResponse(_('Individual/seed not found'))

    try:
        catalog = SeedCatalog.objects.get(id=catalogId)
    except:
        return HttpResponse(_('Seed catalog not found'))

    catalog.seed.add(seed)
    catalog.save()

    if "_redirect" in request.GET:
        return HttpResponseRedirect(request.GET["_redirect"])

    message = _('%(seed)s added to %(catalog)s') % {'seed': seed, 'catalog': catalog}

    return render_catalog_edit(
        request=request, catalog=catalog,
        inline="inline" in request.GET,
        message=message,
    )


def generate_catalog(request, catalog: SeedCatalog):
    import os
    import shutil
    import subprocess
    import select

    seeds = catalog.seed.all().exclude(seed_available=False).order_by(
        'species__family__family',
        'species__family__genus', 'species__species',
        'species__subspecies', 'species__variety'
    )
    c = {
        "catalog": catalog,
        "seeds": seeds,
    }
    t = loader.get_template('seedcatalog/latex/catalog.tex')
    texContent = t.render(c)

    texDirectory = os.path.join(settings.MEDIA_ROOT, "pdf/catalog/temp")
    workingDirectory = os.path.join(texDirectory, request.COOKIES['sessionid'])
    if os.path.exists(workingDirectory):
        shutil.rmtree(workingDirectory)
    os.makedirs(workingDirectory)
    #os.chdir(workingDirectory)

    filename = os.path.join(
        workingDirectory,
        "%s.%s" % ("catalog", "tex"),
    )

    with open(filename, "w") as fp:
        fp.write(texContent)

    p = subprocess.Popen(
        """
        cd %(wdir)s
        echo /usr/bin/pdflatex -interaction=nonstopmode -file-line-error -output-format pdf %(fn)s
        cd %(wdir)s
        echo "first run:"
        /usr/bin/pdflatex -interaction=nonstopmode -file-line-error -output-format pdf %(fn)s
        echo "second run:"
        /usr/bin/pdflatex -interaction=nonstopmode -file-line-error -output-format pdf %(fn)s
        """ % {
            "wdir": workingDirectory,
            "fn": filename,
        },
        shell=True, stdout=subprocess.PIPE)

    fd_out = p.stdout.fileno()

    poll_object = select.poll()
    poll_object.register(fd_out, select.POLLIN)

    stdoutString, stderrString = b"", b""

    while p.poll() is None:
        for fd, mask in poll_object.poll(100):
            if mask & select.POLLIN:
                if fd == fd_out:
                    stdoutString += os.read(fd, 65535)

    pdfPath = os.path.join(workingDirectory, "catalog.pdf")
    pdfTargetFn = "catalog-%s.pdf" % catalog.id
    pdfTarget = os.path.join(settings.MEDIA_ROOT, "pdf/catalog", pdfTargetFn)

    debugtxt = ""

    # copy pdf output to /media/pdf/catalog
    try:
        os.remove(pdfTarget)
    except:
        pass
    try:
        shutil.move(pdfPath, pdfTarget)
    except:
        debugtxt += "ERROR: %s\n" % (_("Could not move %(pdf)s to %(targetpdf)s") % {
                                        "pdf": pdfPath,
                                        "targetpdf": pdfTarget })
    # remove temp traces..
    os.chdir(settings.BASE_DIR)
    try:
        shutil.rmtree(workingDirectory)
    except:
        pass

    if stderrString:
        debugtxt += "STDERR: %s\n" % stderrString
    debugtxt += "STDOUT: %s\n" % stdoutString

    catalog.debug_output = debugtxt
    catalog.save()


@write_permission_required
def generate_request(request, catalogId):

    try:
        catalog = SeedCatalog.objects.get(id=catalogId)
    except SeedCatalog.DoesNotExist:
        return HttpResponse(_("Unknown seed catalog %s") % str(catalogId))

    generate_catalog(request, catalog)

    return HttpResponseRedirect(reverse("admin:seedcatalog_seedcatalog_changelist"))


@login_required
def debug_view(request, catalogId):
    try:
        catalog = SeedCatalog.objects.get(id=catalogId)
    except SeedCatalog.DoesNotExist:
        return HttpResponse(_("Unknown seed catalog %s") % str(catalogId))

    ctx = minimal_admin_context(request, SeedCatalog, _("LateX debug output"))
    if catalog.debug_output:
        ctx["page_content"] = "<pre>%s</pre>" % escape(
            catalog.debug_output.replace("\\n", "\n")
        )
    return render(request, ctx["admin_base_tmpl"], ctx)


@write_permission_required
def duplicate_catalog_request(request, catalogId):
    try:
        catalog = SeedCatalog.objects.get(id=catalogId)
    except:
        return HttpResponse(_("Unknown seed catalog %s") % str(catalogId))

    new_catalog = catalog.create_duplicate()

    return HttpResponseRedirect(
        reverse("admin:seedcatalog_seedcatalog_change", args=(new_catalog.id,))
    )


@write_permission_required
def finalize_catalog_request(request, catalogId):
    try:
        catalog = SeedCatalog.objects.get(id=catalogId)
    except SeedCatalog.DoesNotExist:
        return HttpResponse(_("Unknown seed catalog %s") % str(catalogId))

    if "seedcatalog.can_finalize_catalog" not in request.user.get_all_permissions():
        ctx = minimal_admin_context(request, SeedCatalog)
        ctx["error"] = _("Sorry, you do not have the permission to finalize the catalog.")
        ctx["page_content"] = '<a href="%s" class="button">%s</a>' % (
            reverse("admin:seedcatalog_seedcatalog_change", args=(catalog.id,)),
            _("Return to catalog")
        )
        return render(request, ctx["admin_base_tmpl"], ctx)

    catalog.is_finalized = not catalog.is_finalized
    catalog.save()

    return HttpResponseRedirect(
        reverse("admin:seedcatalog_seedcatalog_change", args=(catalog.id,))
    )

app/seedcatalog/templates/seedcatalog/change_form.html
{% extends 'admin/change_form.html' %}
{% load i18n %}

{% block submit_buttons_bottom %}
    <div class="submit-row">
        <span style="float:left">
            {{ original.seed.count }} {% trans 'seeds in catalog' %}
        </span>
        {% if not is_new %}
            {% if can_finalize %}
                {% if original.is_finalized %}
                    <a class="catalog-button" href="{% url 'seedcatalog:finalize_catalog' original.id %}"
                       title="{% trans "De-finalize the catalog to change it's contents" %}"
                    >{% trans 'Reopen catalog' %}</a>
                {% else %}
                    <a class="catalog-button" href="{% url 'seedcatalog:finalize_catalog' original.id %}"
                       title="{% trans "Finalize the catalog to make it's contents immutable" %}"
                    >{% trans 'Finalize catalog' %}</a>
                {% endif %}
            {% endif %}
            <a class="catalog-button" href="{% url 'seedcatalog:duplicate_catalog' original.id %}"
               title="{% trans 'Duplicate the current catalog to a new one' %}"
            >{% trans 'Duplicate catalog' %}</a>
        {% endif %}
    </div>
    {{ block.super }}
{% endblock %}

app/seedcatalog/templates/seedcatalog/edit_inline.html
{% load i18n %}

<h1>{{catalog}}</h1>
<div style="margin-bottom: 20px;">
    <a href="{% url 'admin:individuals_seed_changelist' %}">Zu den Samen</a>&nbsp;&nbsp;&nbsp;
    <a href="{% url 'admin:seedcatalog_seedcatalog_changelist' %}}">Zu den Katalogen</a>
</div>

{% if catalog_message %}
    <div style="margin-bottom: 20px;">
        Letzte Aktion: {{ catalog_message }}
    </div>
{% endif %}

<div style="margin-bottom: 20px;"><a href="#samenvorhanden">Zu den Samen, die in diesem Katalog fehlen</a></div>

<table style="border-collapse:collapse;">
    <tr style="background-color: #EEE;">
        <td width="50"></td>
        <td width="50">Bst.Nr.</td>
        <td width="350">Samen</td>
        <td>HC</td><td width="80">vorhanden</td>
        <td width="120">Lager</td>
        <td width="100">Nomenklatur</td>
        <td width="180">aus Katalog entfernen</td>
    </tr>
    {%for seed in seeds %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{seed.order_number}}</td>
            <td><a href="/admin/individuals/seed/{{seed.pk}}/">{{seed}}</a></td>
            <td>{{seed.accession_extension}}</td>
            <td><span class="{% if seed.seed_available %}icon-yes{% else %}icon-no{% endif %}"></span></td>
            <td>{% if seed.seed_in_stock %}auf Lager{%else%}nicht auf Lager{%endif%}</td>
            <td>{%if not seed.species.nomenclature_checked%}
                <a href="/admin/species/species/{{seed.species.pk}}/">prüfen</a>
                {%endif%}
            </td>
            <td><a href="/seedcatalog/remove/{{seed.pk}}/from/{{catalog.pk}}/"
                   data-catalog="{{catalog.pk}}" data-seed="{{seed.pk}}"
                   data-action="remove">entfernen</a>
            </td>
        </tr>
    {%endfor%}
</table>

<br/>
<h2 id="samenvorhanden">Samen ausserhalb dieses Katalogs</h2>
<table style="border-collapse:collapse;">
    <tr style="background-color: #EEE;">
        <td width="50">Bst.Nr.</td>
        <td width="350">Samen</td>
        <td>HC</td><td width="80">vorhanden</td>
        <td width="120">Lager</td>
        <td width="100">Nomenklatur</td>
        <td width="180">aus Katalog entfernen</td>
    </tr>
    {%for seed in allseeds %}
        {% if not seed in seeds %}
            <tr>
                <td>{{seed.order_number}}</td>
                <td><a href="/admin/individuals/seed/{{seed.pk}}/">{{seed}}</a></td>
                <td>{{seed.accession_extension}}</td>
                <td><span class="{% if seed.seed_available %}icon-yes{% else %}icon-no{% endif %}"></span></td>
                <td>{% if seed.seed_in_stock %}auf Lager{%else%}nicht auf Lager{%endif%}</td>
                <td>{%if not seed.species.nomenclature_checked%}
                        <a href="/admin/species/species/{{seed.species.pk}}/">prüfen</a>
                    {%endif%}
                </td>
                <td><a href="/seedcatalog/add/{{seed.pk}}/to/{{catalog.pk}}/"
                       data-catalog="{{catalog.pk}}" data-seed="{{seed.pk}}"
                       data-action="add">hinzufügen</a>
                </td>
            </tr>
        {% endif %}
    {%endfor%}
</table>

app/seedcatalog/templates/seedcatalog/edit_page.html
{% extends admin_base_tmpl %}
{% load i18n static %}

{% block extrahead %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'seedcatalog/edit_page.js' %}"></script>
{% endblock %}

{% block page_content %}

    <div class="seed-catalog-container"
         data-add-url="{% url 'seedcatalog:add_seed' 0 1 %}?inline"
         data-remove-url="{% url 'seedcatalog:remove_seed' 0 1 %}?inline"
    >
        {% include './edit_inline.html' %}
    </div>

{% endblock %}